name: gh-pages

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: Unity

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: dump environment
        run: |
          if [ -z "$UNITY_EMAIL" ]; then
            echo "UNITY_EMAIL is empty"
          fi
          if [ -z "$UNITY_PASSWORD" ]; then
            echo "UNITY_PASSWORD is empty"
          fi
          if [ -z "$UNITY_SERIAL" ]; then
            echo "UNITY_SERIAL is empty"
          fi
          env
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: test-project
          targetPlatform: StandaloneLinux64